version: "3.9"

services:
  backend:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      target: dev
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app

    expose:
      - 80
    ports:
      - 80:80
    